### ISSUE TITLE
Error with VS 2015

### ISSUE THREAD

**Issue by khoavn** [scrubs767/GitStash#6]
I get this message when switching to Git Bash  in Team Explorer

`Error
System.MissingMethodException: Method not found: 'Void GitStash.ViewModels.RecommendedActionsViewModel..ctor(GitWrapper.IGitStashWrapper, TeamExplorer.Common.ITeamExplorerBase)'.
at GitStash.Sections.RecommendedActionsSection.Initialize(Object sender, SectionInitializeEventArgs e)
## at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)

Error
System.MissingMethodException: Method not found: 'Void GitStash.ViewModels.StashesViewModel..ctor(GitWrapper.IGitStashWrapper, TeamExplorer.Common.ITeamExplorerBase, SecondLanguage.Translator)'.
at GitStash.Sections.StashesSection.Initialize(Object sender, SectionInitializeEventArgs e)
at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)`

**Comment by scrubs767** [comment]
You mean GitStash? I'm pretty sure you do, as that error crops up from time to time. I have not been able to reproduce it myself, if I give you a special version can you try it and work with me to solve this issue?

**Comment by khoavn** [comment]
Yes sure, I'm glad to work with you to solve this one. Btw I'm using Resharper and GitFlow for Visual Studio 2015.

**Comment by bmeverett** [comment]
I have the same issue on VS 2015

**Comment by bmeverett** [comment]
@scrubs767  I can't seem to reproduce the issue either. I can run just fine from the debugger in Visual Studio. I will continue to investigate.

**Comment by bmeverett** [comment]
So I ran fuslogwv.exe and it seems that it can't find the main GitStash assembly.  I created a gist with the log 
https://gist.github.com/bmeverett/6d0fa03590f380844aeb70dc0ec5c7e4

Now to look into including this file while installing the extension.

**Comment by bmeverett** [comment]
@scrubs767 Any possibility to add the hacktoberfest label on this issue to generate more traction this month?

**Comment by scrubs767** [comment]
That file is the extension, this sounds more like an installation issue in VS side. the gitstash assembly has almost all the of the code for this extension. BTW I tried but the hacktoberfest label is not showing for me

**Comment by scrubs767** [comment]
I have a build I'd like you to try, if you have the time

**Comment by bmeverett** [comment]
Yea sure, I can take a look

**Comment by scrubs767** [comment]
[GitStash.zip](https://github.com/scrubs767/GitStash/files/591639/GitStash.zip)

give this one a try, just rename it to .vsix and double click to install. 

I believe the issue is because another dll can not be loaded that the gitstash.dll was referencing. This build gits rids of a lot of the dll's I was creating and now everything is signed. There is one external dll, libgitstash2 and of course its native binary dll and that very well might be the cause of the issue. This will narrow it down.

I still have one more trick up my sleeve if this doesn't work by adding an assembly loader

**Comment by bmeverett** [comment]
So the first time I open Visual Studio after installing the new extension, Visual Studio crashes and here is what I could grab from GitStash.  http://imgur.com/KO2Txwd

I debug the Visual Studio crash at it is crashing on:

An unhandled exception of type 'System.TypeInitializationException' occurred in LibGit2Sharp.dll
Additional information: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.

Once I restart Visual Studio, the error goes back to the ones above and Visual Studio doesn't crash.

**Comment by scrubs767** [comment]
Ok I did some more research, I think I may have packaged the native
binaries wrong, yet again this shows no issue on my side.

I will make another build tonight when I get home if you are willing to try
it again.

Steve

**Comment by bmeverett** [comment]
Yep just let me know when you have it and I'll try it out

**Comment by scrubs767** [comment]
[GitStash.zip](https://github.com/scrubs767/GitStash/files/593245/GitStash.zip)
Here you go, same thing, rename and double click to install, this one moves the native binaries into a different directory

**Comment by bmeverett** [comment]
I tried it again, and it seems to be the same issue, crashing on first open and then the same error messages as before.

**Comment by scrubs767** [comment]
[GitStash.zip](https://github.com/scrubs767/GitStash/files/597168/GitStash.zip)
Lets try this again

**Comment by bmeverett** [comment]
It works! 🎉 

On first load I am getting an error that the input string was not in the correct format for the stashes. But that seems to be a different issue.

**Comment by scrubs767** [comment]
Can you send me the error?

**Comment by bmeverett** [comment]
```System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at GitWrapper.GitStashItem..ctor(Stash s) in C:\Users\scrub\Documents\Visual Studio 2015\Projects\GitStash\GitStash\GitWrapper\GitStashItem.cs:line 16
   at GitWrapper.GitStashWrapper.get_Stashes() in C:\Users\scrub\Documents\Visual Studio 2015\Projects\GitStash\GitStash\GitWrapper\GitStashWrapper.cs:line 64
   at GitStash.ViewModels.StashesViewModel.get_Stashes() in C:\Users\scrub\Documents\Visual Studio 2015\Projects\GitStash\GitStash\ViewModels\StashesViewModel.cs:line 37
   at GitStash.Sections.StashesSection.Initialize(Object sender, SectionInitializeEventArgs e) in C:\Users\scrub\Documents\Visual Studio 2015\Projects\GitStash\GitStash\Sections\StashesSection.cs:line 35
   at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)```

**Comment by khoavn** [comment]
Hi scrubs767,

It doesn't crash now but also doesn't work for me, I entered message then click Save button but nothing happened.

Another issue is I can't do quick change to GitStash (from Changes/Branches/Sync), only way to navigate to GitStash is need to go to Home then GitStash.

Thanks for your work.

**Comment by yannduran** [comment]
@khoavn In reference to your inability to *quick change* to GitStash, today I:

1. added issue #7 that describes exactly that problem
2. added pull request #8 with the code to fix issue #7

**Comment by scrubs767** [comment]
I have a commit for this already, thank you

**Comment by scrubs767** [comment]
Sorry that was for the not in the drop down issue, I do have another file for you to try, if you have the time.
[GitStash.zip](https://github.com/scrubs767/GitStash/files/629048/GitStash.zip)

**Comment by bmeverett** [comment]
@scrubs767 I tried the new build and it is back to the first issue where both sections don't load and provide the same error as above.

**Comment by scrubs767** [comment]
Well, I know it an issue with libgit2 not finding it's native dll's, that I
confirmed with the build that didn't crash. I also successfully ran the
build I gave you on my machine which had a special build of libgit2stash,
so there was no chance it could be loading the native dlls from someplace
else on my machine so it must be permissions

**Comment by scrubs767** [comment]
This version I try to load the native dll manually, after this I am at a loss.

[GitStash.zip](https://github.com/scrubs767/GitStash/files/630850/GitStash.zip)

**Comment by bmeverett** [comment]
I got this 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitStash.ViewModels.PageViewModel..ctor(INavigateable page, IGitStashWrapper wrapper)
   at GitStash.StashPage.Initialize(Object sender, PageInitializeEventArgs e) in C:\Users\scrub\Documents\Visual Studio 2015\Projects\GitStash\GitStash\StashPage.cs:line 42 
at Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerPageHost.Initialize(TeamExplorerPageContext context)
```

On top of the other two errors we've been getting

**Comment by scrubs767** [comment]
Did you see any message box show up?

**Comment by bmeverett** [comment]
No

**Comment by yannduran** [comment]
Steve,

Just to let you know, the GitStash extension doesn't work for me either (VS 2015.3). It doesn't cause anything to crash. I can open the Git Stash page, but there's only error messages in it, no actual functionality.

HTH,

Yann

**Comment by bmeverett** [comment]
@yannduran I have been working with Steve as he provides updates to try and get something to work.  All the comments that have a link to with GitStash.zip is an update that I rename to GitStash.vsix to try as he provides new installs.

**Comment by scrubs767** [comment]
Yann, yeah this tough because I can not reproduce, I have a good idea that
libgit2sharp can't find its native dll's but I'm not positive on that. I
was going to rewrite part of it to use another library or the git.exe but
that is a lot of work for me right now.

If someone who has this issue will try and debug it, it might she'd more
light on the matter because right now I have to guess in everything.

The last zip file I uploaded added code to load the dll in the package
constructor and will show a message box if it fails.

**Comment by stefan505** [comment]
I have VS 2015 Update 3 and mine doesn't crash, but it shows the following:

![image](https://cloud.githubusercontent.com/assets/10812446/20918345/349f8158-bb9f-11e6-82be-eb9bc2ee7c1a.png)

Am I missing something is or is there a problem?

**Comment by bmeverett** [comment]
@stefan505 hmm that's what you're supposed to see. However some of us are seeing errors. What version is everyone running (Community, Pro, Enterprise) that might be a possible issue

**Comment by scrubs767** [comment]
It means you have untracked files in the directory, have a look at changes

**Comment by scrubs767** [comment]
I've used Enterprise, professional and Community Edition,  updates 2 and 3

**Comment by yannduran** [comment]
@stefan505 This is what I see when I click on Git Stash:

![image](https://cloud.githubusercontent.com/assets/2031126/20926615/6a47627c-bc11-11e6-90e7-2a80566c2912.png)

@bmeverett I'm using VS 2015.3 Enterprise

**Comment by bmeverett** [comment]
So I stumbled across something about this happening with different extensions. I disabled all my extensions except for Git Stash and it works now. I will try and narrow it down as to what extension may be causing it

**Comment by scrubs767** [comment]
Very interesting, and good work

**Comment by scrubs767** [comment]
@stefan505 A more thorough explanation is that GitStash will not just stash un-versioned files unless you check the box to allow it, in most cases it doesn't make sense. 

An un-versioned file is one NOT being tracked by Git, generally these are things in the solution directory that are either developer specific like a .vs directory or generated files, thing of that nature. However they could be a class file you recently added, but didn't tell Git to track it, an unstaged file, and you may want that stashed without doing a check in because its not done yet.

Now in your particular instance it says you have 0 untracked, and this could happen because gitstash doesn't know about something existing yet and git does. try to close and reopen the project, if that doesn't show it, if you can send me the project your working on, or try to make and example project, but please put it in another issue.

Thank you

**Comment by scrubs767** [comment]
@bmevert GitFlow doesn't use libgit2sharp, it uses the git.exe, besides I use github within VS and that DOES use libgit2sharp, it must be something else, THANK YOU, I will see if I can reproduce the error.

**Comment by scrubs767** [comment]
Ok, I was able to reproduce the error and develop a fix for it. I have GitFlow and GitStash running side by side without errors.  Can anyone that has tried it comment with the version installed, I need to bump it higher to ensure it gets installed correctly

**Comment by scrubs767** [comment]
[GitStash.zip](https://github.com/scrubs767/GitStash/files/635371/GitStash.zip)
This is version 0.9.5, I looked back at the zip files I uploaded for the version number. Please this is only for testing the issue is fixed, don't use it beyond that. This fix borked all my unit tests

**Comment by yannduran** [comment]
I just installed v0.9.5 and there's progress, but there's still an error too.

![image](https://cloud.githubusercontent.com/assets/2031126/20958933/6e19a720-bcac-11e6-9282-e1d4399f9435.png)

**Comment by scrubs767** [comment]
I believe this is a different error because the original error was a dll clash with gitflow, I had used his team explorer api, I removed his code and used one that I had been working on for another project. The fact you can see the page means this error is fixed. I will open a new issue for this one.
